name: language_tutorial
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: tensor-programming <email@example.com>

environment:
  sdk: '>=2.0.0-dev.60.0 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.30
